version: "{build}"
skip_branch_with_pr: true
build: off

environment:
  matrix:
    - nodejs_version: current
    - nodejs_version: lts
    - nodejs_version: 6

platform:
  - x64
  - x86

# Install scripts. (runs after repo cloning)
install:
  # install Node.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - if %nodejs_version% LSS 8 npm i -g npm@6
  - npm install --build-from-source=stdcp

# to run your custom scripts instead of automatic tests
test_script:
  - npm test
  - if "%nodejs_version%"=="lts" npm run build

# to run your custom scripts instead of provider deployments
after_test:
  - if not %nodejs_version% LSS 8 npm run report-coverage

artifacts:
  - path: '**\*.tar.gz'
    name: binding

deploy:
  provider: GitHub
  auth_token:
    secure: 8hqStAGHShwpTpTvpJqw01bteLm0Z1Ob9MdFMevTlCJWb5iVXcr7dpOMGIaOdfSz
  # upload binding to release assets
  artifact: /.*\.tar\.gz/
  on:
    # deploy on tag push only
    appveyor_repo_tag: true
